apiVersion: v1
kind: ConfigMap
metadata:
  name: product-worker-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "techmart.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-worker
data:
  KAFKA_BROKER: "kafka:9092"
