apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: webstore
type: Opaque
stringData:
  POSTGRES_DB: techmart
  POSTGRES_USER: techmart
  POSTGRES_PASSWORD: techmart-secret-pw
  DATABASE_URL: "postgresql://techmart:techmart-secret-pw@postgres:5432/techmart"
