apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "techmart.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  PORT: {{ .Values.api.port | quote }}
