apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "techmart.labels" . | nindent 4 }}
    app: inventory-svc
    app.kubernetes.io/component: inventory-svc
spec:
  selector:
    app: inventory-svc
  ports:
    - port: {{ .Values.inventorySvc.port }}
      targetPort: {{ .Values.inventorySvc.port }}
  type: ClusterIP
